{"uuid": "74642964-7711-45c7-8366-c1fb989135ea", "children": ["1a3a5730-6764-49b5-9c7f-101f7ee51a73"], "befores": [{"name": "init_driver", "status": "passed", "start": 1715136248626, "stop": 1715136259812}], "afters": [{"name": "init_driver::pytest_exception_interact", "status": "broken", "statusDetails": {"message": "TypeError: init_driver.<locals>.pytest_exception_interact() missing 3 required positional arguments: 'node', 'call', and 'report'\n", "trace": "  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSelenium\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1715136261946, "stop": 1715136261948}, {"name": "init_driver::quit", "status": "passed", "start": 1715136261948, "stop": 1715136265807}], "start": 1715136248626, "stop": 1715136265807}